version: "3"

services:
    nginx:
        image: nginx:1.17-alpine
        restart: always
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./../public:/var/app/public

    fpm:
        build: fpm
        restart: always
        volumes:
            - ./..:/var/app

    db:
        image: postgres:12.1-alpine
        ports:
            - ${DB_EXTERNAL_PORT}:5432
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_DB=${DB_NAME}
        volumes:
            - db:/var/lib/postgresql/data

volumes:
    db: